import type { Match } from "@/lib/types";

export const mockMatches: Match[] = [
  {
    id: "1",
    homeTeam: "Paris Saint-Germain",
    awayTeam: "Olympique Lyonnais",
    homeProb: 62,
    drawProb: 22,
    awayProb: 16,
    prediction: "HOME",
    confidence: 74,
    isValueBet: false,
    matchDate: "Sat 21:00",
    league: "Ligue 1",
    leagueId: 61,
    homeForm: "WWWDW",
    awayForm: "DLWDL",
  },
  {
    id: "2",
    homeTeam: "Olympique de Marseille",
    awayTeam: "AS Monaco",
    homeProb: 38,
    drawProb: 28,
    awayProb: 34,
    prediction: "HOME",
    confidence: 52,
    isValueBet: true,
    matchDate: "Sun 17:05",
    league: "Ligue 1",
    leagueId: 61,
    homeForm: "WDWLW",
    awayForm: "WWDWL",
  },
  {
    id: "3",
    homeTeam: "Stade Rennais",
    awayTeam: "LOSC Lille",
    homeProb: 29,
    drawProb: 31,
    awayProb: 40,
    prediction: "AWAY",
    confidence: 58,
    isValueBet: false,
    matchDate: "Sun 15:00",
    league: "Ligue 1",
    leagueId: 61,
    homeForm: "LLDWL",
    awayForm: "WWWDW",
  },
  {
    id: "4",
    homeTeam: "Arsenal",
    awayTeam: "Manchester City",
    homeProb: 33,
    drawProb: 27,
    awayProb: 40,
    prediction: "AWAY",
    confidence: 65,
    isValueBet: true,
    matchDate: "Sat 17:30",
    league: "Premier League",
    leagueId: 39,
    homeForm: "WDWWL",
    awayForm: "WWWWW",
  },
  {
    id: "5",
    homeTeam: "Liverpool",
    awayTeam: "Chelsea",
    homeProb: 54,
    drawProb: 24,
    awayProb: 22,
    prediction: "HOME",
    confidence: 71,
    isValueBet: false,
    matchDate: "Sun 16:30",
    league: "Premier League",
    leagueId: 39,
    homeForm: "WWDWW",
    awayForm: "LWDWL",
  },
  {
    id: "6",
    homeTeam: "Real Madrid",
    awayTeam: "FC Barcelona",
    homeProb: 45,
    drawProb: 26,
    awayProb: 29,
    prediction: "HOME",
    confidence: 60,
    isValueBet: false,
    matchDate: "Sat 21:00",
    league: "La Liga",
    leagueId: 140,
    homeForm: "WWWLW",
    awayForm: "WDWWL",
  },
  {
    id: "7",
    homeTeam: "Atletico Madrid",
    awayTeam: "Sevilla FC",
    homeProb: 56,
    drawProb: 25,
    awayProb: 19,
    prediction: "HOME",
    confidence: 78,
    isValueBet: false,
    matchDate: "Sun 18:30",
    league: "La Liga",
    leagueId: 140,
    homeForm: "WWWWD",
    awayForm: "DLLWL",
  },
  {
    id: "8",
    homeTeam: "Bayern Munich",
    awayTeam: "Real Madrid",
    homeProb: 42,
    drawProb: 25,
    awayProb: 33,
    prediction: "HOME",
    confidence: 55,
    isValueBet: true,
    matchDate: "Wed 21:00",
    league: "Champions League",
    leagueId: 2,
    homeForm: "WWDWW",
    awayForm: "WWLWW",
  },
];
